### ISSUE TITLE
2.0.0版本插件报错

### ISSUE THREAD

**Issue by FirstMemory** [dromara/easy-es#134]
Caused by: java.lang.RuntimeException: Could not find method on interface org.dromara.easyes.core.kernel.BaseEsMapper named selectList. Cause: java.lang.NoSuchMethodException: org.dromara.easyes.core.kernel.BaseEsMapper.selectList(org.dromara.easyes.core.conditions.select.LambdaEsQueryWrapper)
	at org.dromara.easyes.extension.plugins.Plugin.getSignatureMap(Plugin.java:83) ~[easy-es-extension-2.0.0.jar:2.0.0]
	at org.dromara.easyes.extension.plugins.Plugin.wrap(Plugin.java:48) ~[easy-es-extension-2.0.0.jar:2.0.0]
	at org.dromara.easyes.extension.context.Interceptor.plugin(Interceptor.java:24) ~[easy-es-extension-2.0.0.jar:2.0.0]
	at org.dromara.easyes.extension.context.InterceptorChain.pluginAll(InterceptorChain.java:31) ~[easy-es-extension-2.0.0.jar:2.0.0]
	at org.dromara.easyes.starter.register.MapperFactoryBean.getObject(MapperFactoryBean.java:98) ~[easy-es-boot-starter-2.0.0.jar:2.0.0]
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:169) ~[spring-beans-5.3.27.jar:5.3.27]
	... 90 common frames omitted
Caused by: java.lang.NoSuchMethodException: org.dromara.easyes.core.kernel.BaseEsMapper.selectList(org.dromara.easyes.core.conditions.select.LambdaEsQueryWrapper)
	at java.base/java.lang.Class.getMethod(Class.java:2227) ~[na:na]
	at org.dromara.easyes.extension.plugins.Plugin.getSignatureMap(Plugin.java:80) ~[easy-es-extension-2.0.0.jar:2.0.0]
	... 95 common frames omitted

**Comment by Sxxjava** [comment]
我遇到了一样的问题
