### ISSUE TITLE
使用xxxMapper.createIndex()创建索引报错：Unknown token [VALUE_NULL] in alias [ee_default_alias]

### ISSUE THREAD

**Issue by yangjinde** [dromara/easy-es#137]
Hi，我在项目启动时通过esTextDocumentMapper.createIndex()方式想创建对应的索引时，报以下错，请问怎么解决？

**### 1、报错如下：**
Suppressed: org.elasticsearch.client.ResponseException: method [PUT], host [http://192.168.88.88:19200], URI [/text_document?master_timeout=30s&timeout=30s], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Unknown token [VALUE_NULL] in alias [ee_default_alias]"}],"type":"illegal_argument_exception","reason":"Unknown token [VALUE_NULL] in alias [ee_default_alias]"},"status":400}
		at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:326)
		at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296)
		at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)
		at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1654)
		... 95 common frames omitted

**### 2、EsTextDocumentMapper 代码如下：**
`import org.dromara.easyes.core.kernel.BaseEsMapper;

/**
 * 全文索引检索实体
 *
 * @author ruoyi
 */
public interface EsTextDocumentMapper extends BaseEsMapper<EsTextDocument> {
}`

**### 3、数据模型 EsTextDocument如下：**
`import lombok.Data;
import org.dromara.easyes.annotation.HighLight;
import org.dromara.easyes.annotation.IndexField;
import org.dromara.easyes.annotation.IndexId;
import org.dromara.easyes.annotation.IndexName;
import org.dromara.easyes.annotation.rely.Analyzer;
import org.dromara.easyes.annotation.rely.FieldType;
import org.dromara.easyes.annotation.rely.IdType;

/**
 * 全文索引 ES数据模型
 *
 * @author yjd65
 */
@Data
@IndexName("text_document")
public class EsTextDocument {
    /**
     * es中的唯一id
     */
    @IndexId(type = IdType.NONE)
    private String id;

    /**
     * 公告ID
     */
    private Long noticeId;

    /**
     * 公告标题
     */
    @HighLight(preTag = "<font color=\"red\">", postTag = "</font>")
    @IndexField(fieldType = FieldType.TEXT, analyzer = Analyzer.IK_SMART, searchAnalyzer = Analyzer.IK_MAX_WORD)
    private String noticeTitle;

    /**
     * 公告类型
     */
    private String noticeType;

    /**
     * 内容
     */
    @HighLight(preTag = "<font color=\"red\">", postTag = "</font>")
    @IndexField(fieldType = FieldType.TEXT, analyzer = Analyzer.IK_SMART, searchAnalyzer = Analyzer.IK_MAX_WORD)
    private String noticeContent;

    /**
     * 公告状态
     */
    private String status;
}`

**Comment by bytefuck** [comment]
我也是遇到同样的问题，估计是版本兼容问题把，es版本是8.15，框架的版本基本上都停留在7.15了

**Comment by A-kun-ya** [comment]
我也是遇到同样的问题，用的实例代码，但是es版本是8.14.3 ，大概率需要降低es的版本才可以使用
